apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app # Ensure this label matches your pod configuration
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80       # Port exposed externally
      targetPort: 8080 # Port your application is listening on
